#!/usr/bin/env python3
"""Fix French accents in documentation HTML files."""
import re
import sys

# Accent fixes: (pattern, replacement) — word-boundary aware
# These only match whole French words, not inside code/attributes
ACCENT_FIXES = [
    # É words
    ('Epreuve', 'Épreuve'), ('epreuve', 'épreuve'),
    ('Numerique', 'Numérique'), ('numerique', 'numérique'),
    ('numeriques', 'numériques'),
    ('securite', 'sécurité'), ('Securite', 'Sécurité'),
    ('securiser', 'sécuriser'), ('Securiser', 'Sécuriser'),
    ('securisees', 'sécurisées'), ('securises', 'sécurisés'),
    ('securisee', 'sécurisée'), ('securise', 'sécurisé'),
    ('Securisation', 'Sécurisation'), ('securisation', 'sécurisation'),
    ('deploiement', 'déploiement'), ('Deploiement', 'Déploiement'),
    ('deployer', 'déployer'), ('deploye', 'déployé'),
    ('developpement', 'développement'), ('Developpement', 'Développement'),
    ('Developper', 'Développer'), ('developper', 'développer'),
    ('Developpeur', 'Développeur'),
    ('donnees', 'données'), ('Donnees', 'Données'), ('donnee', 'donnée'),
    ('creation', 'création'), ('Creation', 'Création'),
    ('methodes', 'méthodes'), ('methode', 'méthode'), ('Methode', 'Méthode'),
    ('memoire', 'mémoire'),
    ('demarrage', 'démarrage'),
    ('demarches', 'démarches'),
    ('referentiels', 'référentiels'), ('referentiel', 'référentiel'),
    ('referentielle', 'référentielle'),
    ('references', 'références'), ('reference', 'référence'),
    ('specifiques', 'spécifiques'), ('specifique', 'spécifique'),
    ('parametres', 'paramètres'), ('parametre', 'paramètre'),
    ('Parametre', 'Paramètre'),
    ('repertoire', 'répertoire'),
    ('problemes', 'problèmes'), ('probleme', 'problème'),
    ('academique', 'académique'),
    ('necessaires', 'nécessaires'), ('necessaire', 'nécessaire'),
    ('necessitant', 'nécessitant'),
    ('etapes', 'étapes'), ('etape', 'étape'), ('Etape', 'Étape'),
    ('defaut', 'défaut'),
    ('generer', 'générer'), ('generee', 'générée'), ('genere', 'généré'),
    ('Generee', 'Générée'), ('generes', 'générés'),
    ('preciser', 'préciser'),
    ('completement', 'complètement'),
    ('complete', 'complète'),
    ('completude', 'complétude'),
    ('deja', 'déjà'),
    ('desactiver', 'désactiver'), ('desactive', 'désactivé'),
    ('desactivation', 'désactivation'), ('Desactivation', 'Désactivation'),
    ('Desactive', 'Désactivé'), ('Desactiver', 'Désactiver'),
    ('evenements', 'événements'), ('evenement', 'événement'),
    ('vulnerabilite', 'vulnérabilité'),
    ('proteger', 'protéger'),
    ('protegees', 'protégées'), ('protegee', 'protégée'), ('protege', 'protégé'),
    ('resultats', 'résultats'), ('resultat', 'résultat'), ('Resultats', 'Résultats'),
    ('Resultat', 'Résultat'),
    ('reponses', 'réponses'), ('reponse', 'réponse'),
    ('Reponses', 'Réponses'), ('Reponse', 'Réponse'),
    ('Repondre', 'Répondre'), ('repondant', 'répondant'), ('repond', 'répond'),
    ('requetes', 'requêtes'), ('requete', 'requête'),
    ('entrees', 'entrées'), ('entree', 'entrée'), ('Entrees', 'Entrées'),
    ('supprime', 'supprimé'), ('supprimes', 'supprimés'),
    ('modifie', 'modifié'), ('modifies', 'modifiés'),
    ('prefere', 'préféré'),
    ('detaillees', 'détaillées'), ('detaillee', 'détaillée'),
    ('detailles', 'détaillés'), ('detaille', 'détaillé'),
    ('presente', 'présenté'), ('presentent', 'présentent'),
    ('cles', 'clés'), ('Cle', 'Clé'),
    ('acces', 'accès'), ('Acces', 'Accès'),
    ('verifier', 'vérifier'), ('Verifier', 'Vérifier'),
    ('verification', 'vérification'),
    ('verifie', 'vérifié'), ('verifiant', 'vérifiant'),
    ('telecharger', 'télécharger'),
    ('telechargement', 'téléchargement'), ('Telechargement', 'Téléchargement'),
    ('telechargee', 'téléchargée'), ('telechargeable', 'téléchargeable'),
    ('integrer', 'intégrer'),
    ('integrees', 'intégrées'), ('integree', 'intégrée'),
    ('integres', 'intégrés'), ('integre', 'intégré'),
    ('integrations', 'intégrations'), ('integration', 'intégration'),
    ('Integrations', 'Intégrations'), ('Integration', 'Intégration'),
    ('integrite', 'intégrité'),
    ('fonctionnalites', 'fonctionnalités'), ('fonctionnalite', 'fonctionnalité'),
    ('Fonctionnalites', 'Fonctionnalités'), ('Fonctionnalite', 'Fonctionnalité'),
    ('confidentialite', 'confidentialité'),
    ('activite', 'activité'),
    ('priorites', 'priorités'), ('priorite', 'priorité'), ('Priorite', 'Priorité'),
    ('propriete', 'propriété'),
    ('proprietaire', 'propriétaire'), ('Proprietaire', 'Propriétaire'),
    ('portabilite', 'portabilité'),
    ('tracabilite', 'traçabilité'), ('Tracabilite', 'Traçabilité'),
    ('connectivite', 'connectivité'),
    ('reproductibilite', 'reproductibilité'),
    ('systemes', 'systèmes'), ('systeme', 'système'),
    ('Systeme', 'Système'),
    ('reseaux', 'réseaux'), ('reseau', 'réseau'),
    ('derniere', 'dernière'), ('dernieres', 'dernières'),
    ('anterieures', 'antérieures'), ('anterieure', 'antérieure'),
    ('anterieur', 'antérieur'),
    ('etre', 'être'),
    ('concu', 'conçu'), ('concue', 'conçue'), ('concues', 'conçues'),
    ('recoit', 'reçoit'), ('recu', 'reçu'),
    ('maitrise', 'maîtrise'),
    ('gerant', 'gérant'), ('gerer', 'gérer'), ('Gerer', 'Gérer'),
    ('geree', 'gérée'), ('gere', 'gère'),
    ('Perimetre', 'Périmètre'), ('perimetre', 'périmètre'),
    ('metiers', 'métiers'), ('metier', 'métier'),
    ('Metrique', 'Métrique'), ('metrique', 'métrique'), ('metriques', 'métriques'),
    ('echeances', 'échéances'), ('echeance', 'échéance'),
    ('echecs', 'échecs'), ('echec', 'échec'), ('Echecs', 'Échecs'),
    ('echouees', 'échouées'), ('echouee', 'échouée'),
    ('ephemere', 'éphémère'),
    ('dechiffrement', 'déchiffrement'),
    ('dechiffre', 'déchiffré'), ('dechiffrer', 'déchiffrer'),
    ('depassement', 'dépassement'),
    ('depassees', 'dépassées'), ('depassee', 'dépassée'),
    ('Deconnexion', 'Déconnexion'), ('deconnexion', 'déconnexion'),
    ('declaratives', 'déclaratives'),
    ('organises', 'organisés'), ('organisees', 'organisées'),
    ('represente', 'représente'), ('representant', 'représentant'),
    ('heritant', 'héritant'),
    ('reutilisables', 'réutilisables'), ('reutilisable', 'réutilisable'),
    ('reutilise', 'réutilisé'),
    ('avancee', 'avancée'),
    ('concernee', 'concernée'),
    ('accordees', 'accordées'), ('accordee', 'accordée'), ('accorde', 'accordé'),
    ('revoquee', 'révoquée'), ('revoque', 'révoqué'),
    ('revocation', 'révocation'), ('Revocation', 'Révocation'),
    ('beneficiaire', 'bénéficiaire'),
    ('creer', 'créer'), ('Creer', 'Créer'),
    ('Createur', 'Créateur'), ('createur', 'créateur'),
    ('hierarchiques', 'hiérarchiques'), ('hierarchique', 'hiérarchique'),
    ('simultanement', 'simultanément'),
    ('retrograder', 'rétrograder'),
    ('epingles', 'épinglés'), ('epingle', 'épinglé'), ('epinglent', 'épinglent'),
    ('epingler', 'épingler'),
    ('immediat', 'immédiat'), ('immediatement', 'immédiatement'),
    ('dediees', 'dédiées'), ('dediee', 'dédiée'),
    ('dedies', 'dédiés'), ('dedie', 'dédié'),
    ('recents', 'récents'), ('recentes', 'récentes'),
    ('recent', 'récent'), ('recente', 'récente'),
    ('reussie', 'réussie'), ('reussis', 'réussis'),
    ('categories', 'catégories'), ('categorie', 'catégorie'),
    ('precedentes', 'précédentes'),
    ('interieur', 'intérieur'),
    ('applique', 'appliqué'),
    ('aleatoire', 'aléatoire'),
    ('executant', 'exécutant'),
    ('executables', 'exécutables'), ('executable', 'exécutable'),
    ('execute', 'exécuté'),
    ('Execution', 'Exécution'), ('execution', 'exécution'),
    ('Prerequis', 'Prérequis'), ('prerequis', 'prérequis'),
    ('dependances', 'dépendances'), ('Dependances', 'Dépendances'),
    ('compile', 'compilé'),
    ('Competences', 'Compétences'), ('competences', 'compétences'),
    ('competence', 'compétence'), ('Competence', 'Compétence'),
    ('Referencement', 'Référencement'), ('referencement', 'référencement'),
    ('implementees', 'implémentées'), ('implementee', 'implémentée'),
    ('implemente', 'implémenté'),
    ('Evaluer', 'Évaluer'), ('evaluer', 'évaluer'),
    ('iteratif', 'itératif'),
    ('Reinitialisation', 'Réinitialisation'), ('reinitialisation', 'réinitialisation'),
    ('Realiser', 'Réaliser'), ('realiser', 'réaliser'),
    ('pensee', 'pensée'),
    ('Prenom', 'Prénom'), ('prenom', 'prénom'),
    ('metadonnees', 'métadonnées'),
    ('uploade', 'uploadé'), ('uploades', 'uploadés'),
    ('auto-incremente', 'auto-incrémenté'),
    ('affiche', 'affiché'),
    ('hexadecimale', 'hexadécimale'),
    ('associe', 'associé'),
    ('incremental', 'incrémental'), ('incrementales', 'incrémentales'),
    ('incrementation', 'incrémentation'),
    ('Numerotation', 'Numérotation'),
    ('actualise', 'actualisé'),
    ('independamment', 'indépendamment'),
    ('personnalises', 'personnalisés'), ('personnalisee', 'personnalisée'),
    ('personnalise', 'personnalisé'),
    ('prive', 'privé'), ('prives', 'privés'),
    ('supervise', 'supervisé'),
    ('etendues', 'étendues'),
    ('taches', 'tâches'), ('tache', 'tâche'),
    ('Taches', 'Tâches'), ('Tache', 'Tâche'),
    ('apres', 'après'),
    ('libelles', 'libellés'), ('Libelle', 'Libellé'), ('libelle', 'libellé'),
    ('compatibilite', 'compatibilité'),
    ('salaries', 'salariés'),
    ('equipe', 'équipe'), ('Equipe', 'Équipe'),
    ('interconnectes', 'interconnectés'),
    ('identifie', 'identifié'),
    ('repartis', 'répartis'), ('reparties', 'réparties'),
    ('Repartition', 'Répartition'), ('repartition', 'répartition'),
    ('pondere', 'pondéré'), ('ponderes', 'pondérés'), ('ponderee', 'pondérée'),
    ('mecanisme', 'mécanisme'), ('Mecanisme', 'Mécanisme'),
    ('deblocages', 'déblocages'), ('deblocage', 'déblocage'),
    ('Deblocages', 'Déblocages'), ('Deblocage', 'Déblocage'),
    ('debloquer', 'débloquer'), ('debloque', 'débloqué'),
    ('centralisee', 'centralisée'), ('centralise', 'centralisé'),
    ('prevoyance', 'prévoyance'), ('Prevoyance', 'Prévoyance'),
    ('premiere', 'première'),
    ('Sante', 'Santé'), ('sante', 'santé'),
    ('decouplee', 'découplée'), ('decouple', 'découplé'),
    ('Critere', 'Critère'), ('critere', 'critère'),
    ('Evolution', 'Évolution'), ('evolution', 'évolution'),
    ('Epargne', 'Épargne'), ('epargne', 'épargne'),
    ('Deplacement', 'Déplacement'), ('deplacement', 'déplacement'),
    ('reduire', 'réduire'),
    ('referencer', 'référencer'),
    ('responsabilites', 'responsabilités'),
    ('responsabilite', 'responsabilité'),
    ('Responsabilite', 'Responsabilité'),
    ('separation', 'séparation'),
    ('predefinies', 'prédéfinies'), ('predefinir', 'prédéfinir'),
    ('reordonnables', 'réordonnables'), ('reordonnancement', 'réordonnancement'),
    ('Reglement', 'Règlement'), ('reglement', 'règlement'),
    ('ameliorant', 'améliorant'),
    ('semantique', 'sémantique'),
    ('optimise', 'optimisé'),
    ('decalees', 'décalées'),
    ('detecte', 'détecte'), ('detectes', 'détectés'),
    ('Detection', 'Détection'), ('detection', 'détection'),
    ('echappement', 'échappement'), ('Echappement', 'Échappement'),
    ('echappes', 'échappés'), ('echappe', 'échappé'),
    ('identite', 'identité'),
    ('Empeche', 'Empêche'), ('empeche', 'empêche'),
    ('repudiation', 'répudiation'),
    ('modeles', 'modèles'), ('modele', 'modèle'),
    ('differents', 'différents'), ('different', 'différent'),
    ('differenciation', 'différenciation'),
    ('differenciees', 'différenciées'), ('differenciee', 'différenciée'),
    ('generalement', 'généralement'),
    ('general', 'général'), ('General', 'Général'),
    ('entierement', 'entièrement'),
    ('commente', 'commenté'),
    ('francais', 'français'),
    ('differe', 'différé'),
    ('Previsualisation', 'Prévisualisation'), ('previsualisation', 'prévisualisation'),
    ('coherent', 'cohérent'),
    ('pedagogique', 'pédagogique'),
    ('complementaires', 'complémentaires'), ('complementaire', 'complémentaire'),
    ('persistes', 'persistés'),
    ('reserves', 'réservés'), ('reservee', 'réservée'),
    ('rejetee', 'rejetée'),
    ('renomme', 'renommé'),
    ('synthetique', 'synthétique'),
    ('demonstrant', 'démontrant'),
    ('expose', 'exposé'),
    ('prefixes', 'préfixés'), ('prefixe', 'préfixé'),
    ('echeant', 'échéant'),
    ('partagees', 'partagées'), ('partages', 'partagés'),
    ('journalisee', 'journalisée'), ('journalisees', 'journalisées'),
    ('enregistree', 'enregistrée'), ('enregistrees', 'enregistrées'),
    ('capturees', 'capturées'),
    ('acceptees', 'acceptées'),
    ('specifie', 'spécifié'),
    ('automatises', 'automatisés'), ('automatisee', 'automatisée'),
    ('configuree', 'configurée'), ('configure', 'configuré'),
    ('revise', 'révisé'),
    ('verrouilles', 'verrouillés'),
    ('reel', 'réel'),
    ('controle', 'contrôle'), ('Controle', 'Contrôle'),
    ('deposer', 'déposer'),
    ('demontage', 'démontage'),
    ('superieur', 'supérieur'),
    ('Recuperation', 'Récupération'), ('recuperation', 'récupération'),
    ('dupliquee', 'dupliquée'),
    ('unifiee', 'unifiée'),
    ('flexibilite', 'flexibilité'),
    ('adhesion', 'adhésion'),
    ('effectuees', 'effectuées'),
    ('expires', 'expirés'), ('expirees', 'expirées'), ('expiree', 'expirée'),
    ('meteo', 'météo'), ('Meteo', 'Météo'),
    ('temperature', 'température'),
    ('anticipe', 'anticipé'),
    ('Numero', 'Numéro'), ('numero', 'numéro'),
    ('limitee', 'limitée'),
    ('structuree', 'structurée'), ('structure', 'structuré'),
    ('operee', 'opérée'),
    ('operees', 'opérées'),
    ('ete', 'été'),
    ('capacite', 'capacité'),
    ('Developpeur', 'Développeur'),
    ('omnipresents', 'omniprésents'),
    ('filtrable', 'filtrable'),
    ('refonte', 'refonte'),
    ('suspendus', 'suspendus'),
    ('pedagogique', 'pédagogique'),
    ('Reservation', 'Réservation'), ('reservation', 'réservation'),
    ('Reservations', 'Réservations'), ('reservations', 'réservations'),
    ('Prevention', 'Prévention'), ('prevention', 'prévention'),
    ('teletravail', 'télétravail'),
    ('trombinoscope', 'trombinoscope'),
    ('etat', 'état'), ('Etat', 'État'),
    ('completee', 'complétée'),
    ('presentee', 'présentée'),
    ('exploitee', 'exploitée'),
    ('regle', 'règle'), ('regles', 'règles'),
    ('conges', 'congés'), ('conge', 'congé'),
    ('Conges', 'Congés'),
    ('impots', 'impôts'),
    ('Acces', 'Accès'),
    ('Delai', 'Délai'), ('delai', 'délai'),
    ('Securite', 'Sécurité'),
]

def fix_file(filepath):
    """Fix French accents in an HTML file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Protect <pre><code>...</code></pre> blocks and inline <code>...</code>
    # We only protect <pre> blocks (code listings), NOT inline <code> in text
    code_blocks = []
    def protect_pre(m):
        code_blocks.append(m.group(0))
        return f'__PRECODE_{len(code_blocks)-1}__'

    protected = re.sub(r'<pre[^>]*>.*?</pre>', protect_pre, content, flags=re.DOTALL)

    # Also protect style blocks
    style_blocks = []
    def protect_style(m):
        style_blocks.append(m.group(0))
        return f'__STYLE_{len(style_blocks)-1}__'

    protected = re.sub(r'<style[^>]*>.*?</style>', protect_style, protected, flags=re.DOTALL)

    total_changes = 0

    # Apply accent fixes with word boundaries
    for old, new in ACCENT_FIXES:
        if old == new:
            continue
        # Use word boundary that works with French chars
        pattern = r'(?<![a-zA-ZÀ-ÿ\-])' + re.escape(old) + r'(?![a-zA-ZÀ-ÿ])'
        protected, n = re.subn(pattern, new, protected)
        total_changes += n

    # Fix 'cle' separately (avoid matching 'article', etc.)
    protected, n = re.subn(r'(?<![a-zA-ZÀ-ÿ])cle(?![a-zA-ZÀ-ÿ])', 'clé', protected)
    total_changes += n

    # Fix 'a' -> 'à' for preposition patterns
    preposition_fixes = [
        (' a l\'', ' à l\''),
        (' a la ', ' à la '),
        (' a une ', ' à une '),
        (' a un ', ' à un '),
        (' a des ', ' à des '),
        (' a chaque ', ' à chaque '),
        (' a tous ', ' à tous '),
        (' a tout ', ' à tout '),
        (' a cette ', ' à cette '),
        (' a partir', ' à partir'),
        (' a jour', ' à jour'),
        (' a distance', ' à distance'),
        ('>a l\'', '>à l\''),
        ('adapté à ', 'adapté à '),  # already fixed by above
        ('accès a ', 'accès à '),
        ('droit a ', 'droit à '),
        ('liée a ', 'liée à '),
        ('liées a ', 'liées à '),
        ('lié a ', 'lié à '),
        ('liés a ', 'liés à '),
        ('assigné a ', 'assigné à '),
        ('grâce a ', 'grâce à '),
        ('grace a ', 'grâce à '),
        ('accessible a ', 'accessible à '),
        ('permet a ', 'permet à '),
        ('permettre a ', 'permettre à '),
        ('quitte a ', 'quitte à '),
        ('attribué a ', 'attribué à '),
        ('contribue a ', 'contribue à '),
        ('mis a ', 'mis à '),
        ('mise a ', 'mise à '),
        ('adapté a ', 'adapté à '),
        ('connecte a ', 'connecté à '),
        (' ou chaque', ' où chaque'),
    ]
    for old, new in preposition_fixes:
        if old in protected:
            count = protected.count(old)
            protected = protected.replace(old, new)
            total_changes += count

    # Restore code blocks
    for i, block in enumerate(style_blocks):
        protected = protected.replace(f'__STYLE_{i}__', block)
    for i, block in enumerate(code_blocks):
        protected = protected.replace(f'__PRECODE_{i}__', block)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(protected)

    print(f'  {filepath}: {total_changes} changes')
    return total_changes


# Process all 4 files
files = [
    '/mnt/c/Users/SMIR/Desktop/Sagario/portfolio-smir/public/docs/familidocs-doc.html',
    '/mnt/c/Users/SMIR/Desktop/Sagario/portfolio-smir/public/docs/earth-sanitation-doc.html',
    '/mnt/c/Users/SMIR/Desktop/Sagario/portfolio-smir/public/docs/cpms_v1.html',
    '/mnt/c/Users/SMIR/Desktop/Sagario/portfolio-smir/public/docs/cpms_v2.html',
]

total = 0
for f in files:
    total += fix_file(f)
print(f'\nTotal changes across all files: {total}')
